### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by daproject85** [TachyonRSA/PoGoTos#3]
it says accepted, but when I run server.py it says its not active

**Comment by xneo64** [comment]
+1
happens to me as well.
The accounts I'm trying to activate have been created more than 2 days ago though, is this a problem?

**Comment by TachyonRSA** [comment]
Are these Google or PTC accounts?

**Comment by daproject85** [comment]
pTC

**Comment by TachyonRSA** [comment]
Shouldn't be an issue, what error are you getting in server.py?

**Comment by daproject85** [comment]
2016-08-07 11:55:05,803 [ search_worker_0][      auth_ptc][   ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-07 11:55:05,817 [ search_worker_0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/Users/Rocky/Pokemon/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/Users/Rocky/Pokemon/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']

**Comment by TachyonRSA** [comment]
Stupid question but you sure the username and password combo was correct?

**Comment by xneo64** [comment]
Hi @TachyonRSA 

Here's a similar dump from my side:

# /usr/local/lib/python2.7.9/bin/python runserver.py -ns -l '35.8703284203, 14.5148151877' -st 4 -a ptc -u 98fSra4drQ0GSvr -p rXqEQP24m4UAn3O

2016-08-07 21:05:45,895 [      MainThread][     runserver][    INFO] Parsed location is: 35.8703/14.5148/0.0000 (lat/lng/alt)
2016-08-07 21:05:45,905 [      MainThread][        models][    INFO] Connecting to MySQL database on 127.0.0.1:3306
2016-08-07 21:05:45,915 [   search_thread][        search][    INFO] Search overseer starting
2016-08-07 21:05:45,916 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-07 21:05:45,917 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-07 21:05:45,918 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 2)
2016-08-07 21:05:45,921 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: 98fSra4drQ0GSvr
2016-08-07 21:05:46,814 [ search_worker_0][      auth_ptc][   ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-07 21:05:46,881 [ search_worker_0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/root/pogo3/PokemonGo-Map/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/root/pogo3/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']

Credentials are correct (they used to work previously when ToS wasn't enforced). I've tried with a separate ptc account which I created manually, and runserver.py runs fine with that.

Is there anything else I can check ?

**Comment by justsomedudeonthenet** [comment]
I to have had this happen, but only to some of my accounts.  All the accounts that had the issue were made a different way than the accounts that worked.

My guess would be that they haven't actually clicked the email confirmation link.

**Comment by TachyonRSA** [comment]
> My guess would be that they haven't actually clicked the email confirmation link.

I am thinking that as well.

**Comment by xneo64** [comment]
If it helps, i used this script to create the ptc accounts

https://github.com/jepayne1138/PTCAccount

This was pre API change, doesn't work properly currently

**Comment by keremkayseri** [comment]
guys can you help me i dont know how to install i have the old bot so now i downloaded the the update with the first file named pokemon go bot master then i click on it and there are 3 files in it. i clicked on the builds only and pulled them into the old bot file with 32 datas in it. then i click on the old bot (pokemon.go.rocketAPIconsole) but then it says that there is a new update so what do i have to do? sorry for bad english i´m german

**Comment by matpag** [comment]
i have the same problem, i create a new account (from pokemon site), confirmed the mail, used to script to accept the TOS but still have:
"Could not retrieve token: As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes."

**Comment by clasherpekka** [comment]
Was there a fix or did the PTC accounts require more confirmation of some sort?

**Comment by blindreaper** [comment]
I am having similar issues, it seems that login returns true regardless of what happens, you may just be getting "Accepted Terms of Service for xxxx" even though it failed.

keyphact/pgoapi#87

**Comment by Spiritvn** [comment]
It's working fine for me today, did you guys verify the emails? @blindreaper  @daproject85
