### ISSUE TITLE
TypeError: __init__() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by russellg89** [TachyonRSA/PoGoTos#4]
Installed requirements and created accounts.txt in the "username1:password1" format.
Getting this error:

> Russells-MBP:pogotos-master Business$ python tos.py accounts.txt
> Traceback (most recent call last):
>   File "tos.py", line 29, in <module>
>     accept_tos(username, password)
>   File "tos.py", line 16, in accept_tos
>     api = PGoApi()
> TypeError: __init__() takes exactly 3 arguments (1 given)

**Comment by russellg89** [comment]
Should I bet putting my username and password in tos.py?

**Comment by TachyonRSA** [comment]
Try again after latest commit :)

**Comment by sjaakbanaan** [comment]
I get the same error right now, but with TypeError: init() takes exactly **2** arguments (1 given). Any idea?
