### ISSUE TITLE
slow down request

### ISSUE THREAD

**Issue by amducious** [TachyonRSA/PoGoTos#5]
I'm getting this randomly

Traceback (most recent call last):
  File "tos.py", line 29, in <module>
    accept_tos(username, password)
  File "tos.py", line 18, in accept_tos
    api.login('ptc', username, password)
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 164, in login
    response = self.app_simulation_login()
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 141, in app_simulation_login
    response = request.call()
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/rpc_api.py", line 141, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man

**Comment by TachyonRSA** [comment]
Please have a look at: https://github.com/TachyonRSA/PoGoTos/pull/6

Busy testing, will probably merge don't expect any issues.

**Comment by TachyonRSA** [comment]
Merged update, please update and revert. https://github.com/TachyonRSA/PoGoTos/commit/e100855c95222158ed0016f80aa19b3a58719737
